image: golang:1.10
stages:
  - build
  - test

before_script:
  - cp -r main /go/src/
  - cd /go/src

build-my-project:
  stage: build
  script:
    - go build main/hello.go

test-my-project:
  stage: test
  script:
    - go test -v -cover .
